ALTER TABLE APPOINTMENT ADD BILL_AMOUNT NUMBER(10,2);
UPDATE APPOINTMENT SET BILL_AMOUNT = 1500 WHERE APPOINTMENT_ID = 3;
UPDATE APPOINTMENT SET BILL_AMOUNT = 2000 WHERE APPOINTMENT_ID = 1;
UPDATE APPOINTMENT SET BILL_AMOUNT = 1800 WHERE APPOINTMENT_ID = 2;

-- 1. Count of patients by gender
SELECT GENDER, COUNT(*) FROM PATIENT GROUP BY GENDER;

-- 2. Count of doctors in each department
SELECT DEPARTMENT_ID, COUNT(*) FROM DOCTOR GROUP BY DEPARTMENT_ID;

-- 3. Total appointments and total bill per doctor
SELECT DOCTOR_ID, COUNT(*) AS TOTAL_APPOINTMENTS, SUM(BILL_AMOUNT) AS TOTAL_BILL
FROM APPOINTMENT
GROUP BY DOCTOR_ID;

-- 4. Count of appointments per diagnosis
SELECT DIAGNOSIS, COUNT(*) FROM APPOINTMENT GROUP BY DIAGNOSIS;

-- 5. Departments with more than 1 doctor
SELECT DEPARTMENT_ID, COUNT(*) FROM DOCTOR GROUP BY DEPARTMENT_ID HAVING COUNT(*) > 1;

-- 6. Total bill per appointment date
SELECT APPOINTMENT_DATE, SUM(BILL_AMOUNT) FROM APPOINTMENT GROUP BY APPOINTMENT_DATE;

-- 7. Total bill per doctor
SELECT DOCTOR_ID, SUM(BILL_AMOUNT) FROM APPOINTMENT GROUP BY DOCTOR_ID;

-- 8. Count of distinct patients
SELECT COUNT(DISTINCT PATIENT_ID) FROM APPOINTMENT;

-- 9. Doctors with more than 1 appointment
SELECT DOCTOR_ID, COUNT(*) FROM APPOINTMENT GROUP BY DOCTOR_ID HAVING COUNT(*) > 1;

-- 10. Average bill amount (overall)
SELECT AVG(BILL_AMOUNT) FROM APPOINTMENT;

-- 11. Average bill amount per doctor
SELECT DOCTOR_ID, AVG(BILL_AMOUNT) FROM APPOINTMENT GROUP BY DOCTOR_ID;
